import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToasterProvider from "@/components/providers/ToasterProvider";
import { AuthProvider } from "@/components/providers/auth-provider";
import TanstackProvider from "@/components/providers/TanstackProvider";
import { ReduxProvider } from "@/components/providers/ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <TanstackProvider>
            <ReduxProvider>
              <Navbar />
              {children}
              <Footer />
            </ReduxProvider>
          </TanstackProvider>
          <ToasterProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
