import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ToasterProvider from "@/components/providers/ToasterProvider";
import { AuthProvider } from "@/components/providers/auth-provider";
import TanstackProvider from "@/components/providers/TanstackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AuthProvider>
          <TanstackProvider>
            <Navbar />
            {children}
            <Footer />
          </TanstackProvider>
          <ToasterProvider />
        </AuthProvider>
      </body>
    </html>
  );
}
